import {describe,test,expect} from 'bun:test';
import {unzipSync,strFromU8} from 'fflate';
import {validateScene,safeSvgInput,type DiagramScene} from './scene';
import {renderDrawio,renderPptx,renderSvg} from './render';
const scene:DiagramScene={version:1,title:'Controlled research flow',width:1200,height:720,nodes:[{id:'input',label:'Research question\n数据与对照',shape:'roundRect',x:80,y:280,width:250,height:120,fill:'#EAF1E3',color:'#294D3A'},{id:'output',label:'Evidence & decision',shape:'diamond',x:760,y:250,width:280,height:180,fill:'#F5EBD8',color:'#294D3A'}],edges:[{id:'edge',from:'input',to:'output',label:'controlled test'}]};
describe('editable diagrams',()=>{
 test('native drawio vertices and connected edges preserve escaped text',()=>{const xml=renderDrawio(scene);expect(xml).toContain('vertex="1"');expect(xml).toContain('edge="1"');expect(xml).toContain('source="input" target="output"');expect(xml).toContain('Evidence &amp; decision');expect(xml).not.toContain('<image');});
 test('PPTX consists of native text shapes and line geometry with no media',async()=>{const zip=unzipSync(await renderPptx(scene));const slide=strFromU8(zip['ppt/slides/slide1.xml']!);expect(slide).toContain('Research question');expect(slide).toContain('数据与对照');expect(slide).toContain('prst="roundRect"');expect(slide).toContain('prst="diamond"');expect(slide).toContain('prst="line"');expect((slide.match(/<p:cxnSp>/g)||[]).length).toBe(scene.edges.length);expect(slide).toContain('<a:stCxn');expect(slide).toContain('<a:endCxn');expect(Object.keys(zip).filter(p=>p.startsWith('ppt/media/')&&!p.endsWith('/'))).toEqual([]);expect(slide).not.toContain('<p:pic>');});
 test('reject invalid references, duplicate IDs and unbounded geometry',()=>{expect(()=>validateScene({...scene,edges:[{id:'bad',from:'missing',to:'output',label:''}]})).toThrow();expect(()=>validateScene({...scene,nodes:[scene.nodes[0],scene.nodes[0]]})).toThrow();expect(()=>validateScene({...scene,width:Infinity})).toThrow();expect(()=>validateScene({...scene,nodes:[{...scene.nodes[0],x:5000}]})).toThrow();});
 test('untrusted SVG cannot inject active preview content or external resources',()=>{for(const bad of ['<svg><script>alert(1)</script></svg>','<svg onload="x"/>','<!DOCTYPE svg><svg/>','<svg><image href="https://example.org/x"/></svg>'])expect(()=>safeSvgInput(bad)).toThrow();expect(safeSvgInput('<svg><rect width="10"/></svg>')).toContain('<rect');const xml=renderSvg({...scene,title:'<script>x</script>'});expect(xml).not.toContain('<script>');expect(xml).toContain('&lt;script&gt;');});
});
