import type { ClaimAnchor, ClaimEvidenceLink, PaperClaim } from "@fastwrite/shared";
import { ApiError } from "../http";
import type { JsonDatabase } from "../storage/database";
import type { WorkspaceService } from "../workspace/workspace-service";

const now = () => new Date().toISOString();
export class ClaimService {
  constructor(private readonly database: JsonDatabase, private readonly workspaces: WorkspaceService) {}
  async scan(projectId: string): Promise<PaperClaim[]> {
    const project = this.workspaces.getProject(projectId); const files = await this.workspaces.tree(projectId); const paths = textPaths(files); const found: PaperClaim[] = [];
    for (const path of [project.mainDocument, ...paths.filter((p) => p !== project.mainDocument)]) { const file = await this.workspaces.readTextFile(projectId, path); const candidates = [...file.content.matchAll(/[^.!?\n]{20,}(?:shows?|demonstrates?|improves?|reduces?|increases?|achieves?|outperforms?)[^.!?\n]*[.!?]/gi), ...file.content.matchAll(/[^.!?\n]{20,}(?:\\cite\{[^}]+\}|\d+(?:\.\d+)?\s*%)[^.!?\n]*[.!?]/gi)]; const seen = new Set<number>(); for (const match of candidates) { if (seen.has(match.index ?? -1)) continue; seen.add(match.index ?? -1); const exactText = match[0].trim(); const startOffset = (match.index ?? 0) + match[0].indexOf(exactText); const anchor: ClaimAnchor = { path, fileVersion: file.file.version, startOffset, endOffset: startOffset + exactText.length, exactText, prefix: file.content.slice(Math.max(0, startOffset - 40), startOffset), suffix: file.content.slice(startOffset + exactText.length, startOffset + exactText.length + 40) }; const numbers = [...exactText.matchAll(/(\d+(?:\.\d+)?)\s*(%|ms|s|×|x)?/g)].map((item) => ({ raw: item[0], normalized: Number(item[1]), ...(item[2] ? { unit: item[2] } : {}) })); found.push({ id: `claim_${crypto.randomUUID()}`, projectId, anchor, type: /contribution|propose|introduce/i.test(exactText) ? "contribution" : /method|algorithm|model/i.test(exactText) ? "method" : /limitation|cannot|future work/i.test(exactText) ? "limitation" : /result|improv|reduc|increase|outperform|\d+(?:\.\d+)?\s*%/i.test(exactText) ? "result" : "background", surface: /\\cite\{/i.test(exactText) ? "citation" : /\d+(?:\.\d+)?\s*%/.test(exactText) ? "number" : /caption/i.test(path) ? "caption" : "text", numbers: numbers.length ? numbers : undefined, reviewStatus: "detected", anchorStatus: "current", createdBy: "scanner", createdAt: now(), updatedAt: now() }); } }
    return this.database.mutate((state) => {
      const previous = state.paperClaims.filter((claim) => claim.projectId === projectId);
      const used = new Set<string>();
      const merged: PaperClaim[] = found.map((candidate): PaperClaim => {
        const normalized = candidate.anchor.exactText.replace(/\s+/g, " ").trim();
        const match = previous.find((old) => !used.has(old.id) && old.anchor.path === candidate.anchor.path && old.anchor.exactText.replace(/\s+/g, " ").trim() === normalized);
        if (!match) return { ...candidate, normalizedText: normalized };
        used.add(match.id);
        return { ...match, anchor: candidate.anchor, anchorStatus: "current" as const, updatedAt: now(), normalizedText: normalized };
      });
      for (const old of previous) if (!used.has(old.id)) merged.push({ ...old, anchorStatus: "stale", updatedAt: now() });
      const versions = new Map(found.map((claim) => [claim.anchor.path, claim.anchor.fileVersion]));
      for (const link of state.claimEvidenceLinks) if (link.kind === "workspace" && state.paperClaims.some((claim) => claim.projectId === projectId && claim.id === link.claimId)) link.stale = versions.get(link.path) !== link.anchor.fileVersion;
      state.paperClaims = state.paperClaims.filter((claim) => claim.projectId !== projectId); state.paperClaims.push(...merged); return merged;
    });
  }
  list(projectId: string): PaperClaim[] { this.workspaces.getProject(projectId); return this.database.snapshot().paperClaims.filter((claim) => claim.projectId === projectId); }
  async reanchor(projectId: string, claimId: string): Promise<PaperClaim> { this.workspaces.getProject(projectId); const current = this.database.snapshot().paperClaims.find((item) => item.projectId === projectId && item.id === claimId); if (!current) throw new ApiError(404, "claim_not_found", "Claim not found"); const file = await this.workspaces.readTextFile(projectId, current.anchor.path); const offset = file.content.indexOf(current.anchor.exactText); return this.database.mutate((state) => { const claim = state.paperClaims.find((item) => item.id === claimId)!; if (offset < 0) claim.anchorStatus = "orphaned"; else { claim.anchor = { ...claim.anchor, fileVersion: file.file.version, startOffset: offset, endOffset: offset + claim.anchor.exactText.length, prefix: file.content.slice(Math.max(0, offset - 40), offset), suffix: file.content.slice(offset + claim.anchor.exactText.length, offset + claim.anchor.exactText.length + 40) }; claim.anchorStatus = "reanchored"; } claim.updatedAt = now(); return claim; }); }
  async update(projectId: string, claimId: string, updates: Partial<Pick<PaperClaim, "reviewStatus" | "anchorStatus">>): Promise<PaperClaim> { this.workspaces.getProject(projectId); return this.database.mutate((state) => { const claim = state.paperClaims.find((item) => item.projectId === projectId && item.id === claimId); if (!claim) throw new ApiError(404, "claim_not_found", "Claim not found"); if (updates.reviewStatus === "supported") { const links = state.claimEvidenceLinks.filter((link) => link.claimId === claimId); const valid = links.some((link) => link.kind === "review-waiver" || link.kind === "workspace" || (link.kind === "literature" && state.sourceEvidence.some((evidence) => evidence.id === link.evidenceId && evidence.status === "approved"))); if (!valid) throw new ApiError(409, "claim_evidence_required", "A claim cannot be marked supported without approved evidence or a user waiver"); } if (updates.reviewStatus) claim.reviewStatus = updates.reviewStatus; if (updates.anchorStatus) claim.anchorStatus = updates.anchorStatus; claim.updatedAt = now(); return claim; }); }
  async link(projectId: string, claimId: string, link: Omit<ClaimEvidenceLink, "id" | "claimId">): Promise<ClaimEvidenceLink> { this.workspaces.getProject(projectId); return this.database.mutate((state) => { const raw = link as any; if (!state.paperClaims.some((claim) => claim.projectId === projectId && claim.id === claimId)) throw new ApiError(404, "claim_not_found", "Claim not found"); if (raw.kind === "literature" && !state.sourceEvidence.some((evidence) => evidence.id === raw.evidenceId && evidence.projectId === projectId)) throw new ApiError(400, "evidence_not_found", "Evidence does not belong to this project"); if (raw.kind === "review-waiver" && raw.approvedByUser !== true) throw new ApiError(400, "waiver_requires_user", "Review waiver requires explicit user approval"); const created = { ...raw, id: `claim_link_${crypto.randomUUID()}`, claimId } as ClaimEvidenceLink; state.claimEvidenceLinks.push(created); return created; }); }
  async unlink(projectId: string, claimId: string, linkId: string): Promise<void> { this.workspaces.getProject(projectId); await this.database.mutate((state) => { state.claimEvidenceLinks = state.claimEvidenceLinks.filter((link) => !(link.claimId === claimId && link.id === linkId)); }); }
}

function textPaths(nodes: any[]): string[] { return nodes.flatMap((node) => node.type === "directory" ? textPaths(node.children) : node.kind === "text" && /\.tex$/i.test(node.path) ? [node.path] : []); }
