import { useEffect, useState } from "react";
import './diagrams.css';

type Node = { id:string; label:string; x:number; y:number; width:number; height:number; fill:string; color:string; shape:string };
type Scene = { version:1; title:string; width:number; height:number; nodes:Node[]; edges:Array<{id:string;from:string;to:string;label:string}> };
type Record = {id:string;state:string;scene?:Scene;title?:string;error?:string};
function edgePoints(a:Node,b:Node){const ax=a.x+a.width/2,ay=a.y+a.height/2,bx=b.x+b.width/2,by=b.y+b.height/2;const horizontal=Math.abs(bx-ax)/Math.max(1,(a.width+b.width)/2)>=Math.abs(by-ay)/Math.max(1,(a.height+b.height)/2);return horizontal?{x1:ax+(bx>=ax?1:-1)*a.width/2,y1:ay,x2:bx-(bx>=ax?1:-1)*b.width/2,y2:by}:{x1:ax,y1:ay+(by>=ay?1:-1)*a.height/2,x2:bx,y2:by-(by>=ay?1:-1)*b.height/2};}
const sample:Scene={version:1,title:"可复现科研流程",width:1200,height:720,nodes:[{id:"question",label:"研究问题\n预注册假设",shape:"roundRect",x:60,y:250,width:200,height:110,fill:"#EDF3E8",color:"#294D3A"},{id:"data",label:"数据与对照\n固定划分 / 独立种子",shape:"roundRect",x:350,y:250,width:220,height:110,fill:"#E6F0F5",color:"#294D3A"},{id:"evaluate",label:"执行实验\n记录结果与不确定性",shape:"roundRect",x:660,y:250,width:230,height:110,fill:"#E6F0F5",color:"#294D3A"},{id:"decision",label:"结论与下一步\n保留可复现证据",shape:"roundRect",x:980,y:250,width:180,height:110,fill:"#F6EDDB",color:"#294D3A"}],edges:[{id:"edge1",from:"question",to:"data",label:"操作化"},{id:"edge2",from:"data",to:"evaluate",label:"受控比较"},{id:"edge3",from:"evaluate",to:"decision",label:"证据约束"}]};
async function api(path:string,body?:unknown){const r=await fetch('/api/diagrams'+path,{...(body?{method:'POST',body:JSON.stringify(body),headers:{'content-type':'application/json'}}:{})});const data=await r.json();if(!r.ok)throw new Error(data.error?.message||'请求失败');return data;}
export function DiagramsPage(){
 const [records,setRecords]=useState<Record[]>([]);const [current,setCurrent]=useState<Record|null>(null);const [scene,setScene]=useState<Scene>(sample);const [instruction,setInstruction]=useState('');const [svg,setSvg]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [editor,setEditor]=useState(false);const [raw,setRaw]=useState('');
 const refresh=async()=>setRecords(await api(''));
 useEffect(()=>{void refresh().catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(!current||!['queued','running'].includes(current.state))return;const timer=setInterval(()=>{void api('/'+current.id).then(r=>{setCurrent(r);if(r.scene){setScene(r.scene);void refresh()}if(r.error)setError(r.error)}).catch(e=>setError(e.message))},2000);return()=>clearInterval(timer)},[current?.id,current?.state]);
 async function action(fn:()=>Promise<void>){setError('');setBusy(true);try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const save=async()=>{const r=await api('',{scene,...(current?.id?{parentId:current.id}:{})});setCurrent(r);await refresh()};
 return <main className="diagram-studio" style={{maxWidth:1450,margin:'0 auto',padding:32}}><header style={{display:'flex',alignItems:'center',justifyContent:'space-between'}}><div><a href="/">← FastWrite</a><h1>科研绘图</h1><p>需求或 SVG → 可编辑图结构 → draw.io / PowerPoint</p></div><span>GPT-6 Astra · gpt-6-astra</span></header>
 {error&&<p role="alert" style={{padding:16,background:'#fff0e7',color:'#943c26'}}>{error}</p>}
 <div style={{display:'grid',gridTemplateColumns:'320px minmax(0,1fr)',gap:28}}><aside style={{border:'1px solid #ccd7d0',padding:20,borderRadius:10}}><form onSubmit={e=>{e.preventDefault();void action(async()=>{setCurrent(await api('/generate',{instruction,svg,model:'gpt-6-astra',...(current?.scene?{parentId:current.id}:{})}));await refresh()})}}><label htmlFor="diagram-instruction">绘图需求</label><textarea id="diagram-instruction" style={{width:'100%',minHeight:160,margin:'10px 0'}} value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder="画出检索增强生成的研究流程；区分离线索引和在线问答，用连接线表示证据流。" required maxLength={10000}/><label htmlFor="diagram-svg">参考 SVG（可选）</label><input id="diagram-svg" type="file" accept=".svg,image/svg+xml" onChange={e=>{const f=e.target.files?.[0];if(f){if(f.size>250000){setError('SVG 不得超过 250 KB');return}void f.text().then(setSvg)}}}/>{svg&&<small>已读取 SVG，将作为结构化转换参考。</small>}<button style={{marginTop:20}} disabled={busy||['queued','running'].includes(current?.state||'')}>生成可编辑图</button></form>
 <hr style={{margin:'25px 0'}}/><button onClick={()=>{setCurrent(null);setScene(structuredClone(sample))}}>使用科研流程示例</button><h3>保存的版本</h3>{records.map(r=><button key={r.id} style={{display:'block',margin:'8px 0',textAlign:'left',width:'100%'}} onClick={()=>void action(async()=>{const data=await api('/'+r.id);setCurrent(data);if(data.scene)setScene(data.scene)})}>{r.title||'绘图任务'} · {r.state}</button>)}</aside>
 <section><div style={{display:'flex',gap:15,alignItems:'center',flexWrap:'wrap'}}><button disabled={busy} onClick={()=>void action(save)}>保存新版本</button><button onClick={()=>{setRaw(JSON.stringify(scene,null,2));setEditor(!editor)}}>编辑完整图结构</button>{current?.state==='succeeded'&&['drawio','pptx','svg'].map(format=><a key={format} href={`/api/diagrams/${current.id}/export/${format}`} download={`diagram.${format}`}>下载 {format==='pptx'?'PPTX':format==='drawio'?'draw.io':'SVG'}</a>)}</div>
 {current&&['queued','running'].includes(current.state)&&<p role="status">服务器正在生成图结构，离开页面后可从版本列表查看结果。</p>}
 {editor&&<div><textarea aria-label="图结构 JSON" style={{width:'100%',height:350,fontFamily:'monospace'}} value={raw} onChange={e=>setRaw(e.target.value)}/><button onClick={()=>void action(async()=>{const r=await api('',{scene:JSON.parse(raw),...(current?.id?{parentId:current.id}:{})});setCurrent(r);setScene(r.scene);setEditor(false);await refresh()})}>校验并保存结构</button></div>}
 <h2><input aria-label="图标题" value={scene.title} onChange={e=>setScene({...scene,title:e.target.value})}/></h2><div style={{background:'#fff',border:'1px solid #ccd7d0',borderRadius:10,overflow:'auto'}}><svg role="img" aria-label="可编辑图预览" viewBox={`0 0 ${scene.width} ${scene.height}`} style={{width:'100%',minWidth:600}}><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#557869"/></marker></defs>{scene.edges.map(e=>{const a=scene.nodes.find(n=>n.id===e.from),b=scene.nodes.find(n=>n.id===e.to);if(!a||!b)return null;const p=edgePoints(a,b);return <g key={e.id}><line x1={p.x1} y1={p.y1} x2={p.x2} y2={p.y2} stroke="#557869" strokeWidth={2} markerEnd="url(#arrow)"/><text x={(p.x1+p.x2)/2} y={(p.y1+p.y2)/2-10} textAnchor="middle" fontSize={14}>{e.label}</text></g>})}{scene.nodes.map(n=><g key={n.id}>{n.shape==='ellipse'?<ellipse cx={n.x+n.width/2} cy={n.y+n.height/2} rx={n.width/2} ry={n.height/2} fill={n.fill} stroke="#557869"/>:n.shape==='diamond'?<polygon points={`${n.x+n.width/2},${n.y} ${n.x+n.width},${n.y+n.height/2} ${n.x+n.width/2},${n.y+n.height} ${n.x},${n.y+n.height/2}`} fill={n.fill} stroke="#557869"/>:<rect x={n.x} y={n.y} width={n.width} height={n.height} rx={n.shape==='roundRect'?12:0} fill={n.fill} stroke="#557869"/>}<text fill={n.color} textAnchor="middle" fontSize={18}>{n.label.split('\n').map((line,i,lines)=><tspan key={i} x={n.x+n.width/2} y={n.y+n.height/2+(i-(lines.length-1)/2)*24+6}>{line}</tspan>)}</text></g>)}</svg></div>
 <h3>节点编辑</h3><p>修改文字或位置后保存新版本；导出的 PPTX 包含原生形状和连线。</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}>{scene.nodes.map((n,i)=><fieldset key={n.id} style={{border:'1px solid #ccd7d0',borderRadius:8,padding:12}}><legend>{n.id}</legend><label>文字<textarea aria-label={`节点 ${n.id} 文字`} value={n.label} style={{width:'100%'}} onChange={e=>setScene({...scene,nodes:scene.nodes.map((v,j)=>j===i?{...v,label:e.target.value}:v)})}/></label><div style={{display:'flex',gap:8}}>{(['x','y'] as const).map(axis=><label key={axis}>{axis}<input aria-label={`节点 ${n.id} ${axis}`} type="number" value={n[axis]} style={{width:75}} onChange={e=>setScene({...scene,nodes:scene.nodes.map((v,j)=>j===i?{...v,[axis]:Number(e.target.value)}:v)})}/></label>)}</div></fieldset>)}</div></section></div></main>
}
